"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class upper_body_data_package(object):
    __slots__ = ["isUsed", "curStatusVec", "curErrCodeVec", "curJointPosVec", "curSpeedVec", "curCurrentVec", "curTorqueVec", "endEffectorXYZRPY", "estimated_yaw"]

    __typenames__ = ["int32_t", "int32_t", "int32_t", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, [30], [30], [30], [30], [30], [30], [24], None]

    def __init__(self):
        self.isUsed = 0
        self.curStatusVec = [ 0 for dim0 in range(30) ]
        self.curErrCodeVec = [ 0 for dim0 in range(30) ]
        self.curJointPosVec = [ 0.0 for dim0 in range(30) ]
        self.curSpeedVec = [ 0.0 for dim0 in range(30) ]
        self.curCurrentVec = [ 0.0 for dim0 in range(30) ]
        self.curTorqueVec = [ 0.0 for dim0 in range(30) ]
        self.endEffectorXYZRPY = [ 0.0 for dim0 in range(24) ]
        self.estimated_yaw = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(upper_body_data_package._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.isUsed))
        buf.write(struct.pack('>30i', *self.curStatusVec[:30]))
        buf.write(struct.pack('>30i', *self.curErrCodeVec[:30]))
        buf.write(struct.pack('>30f', *self.curJointPosVec[:30]))
        buf.write(struct.pack('>30f', *self.curSpeedVec[:30]))
        buf.write(struct.pack('>30f', *self.curCurrentVec[:30]))
        buf.write(struct.pack('>30f', *self.curTorqueVec[:30]))
        buf.write(struct.pack('>24f', *self.endEffectorXYZRPY[:24]))
        buf.write(struct.pack(">f", self.estimated_yaw))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != upper_body_data_package._get_packed_fingerprint():
            raise ValueError("Decode error")
        return upper_body_data_package._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = upper_body_data_package()
        self.isUsed = struct.unpack(">i", buf.read(4))[0]
        self.curStatusVec = struct.unpack('>30i', buf.read(120))
        self.curErrCodeVec = struct.unpack('>30i', buf.read(120))
        self.curJointPosVec = struct.unpack('>30f', buf.read(120))
        self.curSpeedVec = struct.unpack('>30f', buf.read(120))
        self.curCurrentVec = struct.unpack('>30f', buf.read(120))
        self.curTorqueVec = struct.unpack('>30f', buf.read(120))
        self.endEffectorXYZRPY = struct.unpack('>24f', buf.read(96))
        self.estimated_yaw = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if upper_body_data_package in parents: return 0
        tmphash = (0x650d4902ee321698) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if upper_body_data_package._packed_fingerprint is None:
            upper_body_data_package._packed_fingerprint = struct.pack(">Q", upper_body_data_package._get_hash_recursive([]))
        return upper_body_data_package._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

